### ISSUE TITLE
cannot change character in waiting room

### ISSUE THREAD

**Issue by tsuncp** [Cleroth/sp_server#10]
only can choose character before entering the lobby , and select the main character

**Comment by Cleroth** [comment]
When I tried it, it only showed one character. If you select that character, the other characters will then show up.
However, someone tells me this used to work originally, so it may be that someone broke it lately.

**Comment by tsuncp** [comment]
yes. I have played sp before.
the character could be easily changed in waiting room.
Now if you choose any other character in waiting room. when you entered the game. the main character will be chosen not the one you chosen.

**Comment by Cleroth** [comment]
By before I meant earlier in the development of this server emulator

**Comment by whitearies** [comment]
I have found this bug

**Comment by tsuncp** [comment]
checked and fixed #19
