### ISSUE TITLE
Main character cannot be changed every time

### ISSUE THREAD

**Issue by tsuncp** [Cleroth/sp_server#11]
not sure is server problem or not, becoz i can't find any similar code about new character?

**Comment by tsuncp** [comment]
updated: I can use the character suddenly. trying to make it happen again

**Comment by Cleroth** [comment]
Works fine for me.

**Comment by tsuncp** [comment]
this bug is long time ago
i will test again

**Comment by tsuncp** [comment]
randomly cannot select main character, however it is rarely , cannot identify the reason
ignore this issue first
