### ISSUE TITLE
Client?

### ISSUE THREAD

**Issue by Unessential** [Cleroth/sp_server#31]
I want to experiment with this server. Where do I find (and how do i modify) a client to connect to a server running this emulator?

**Comment by Unessential** [comment]
Nevermind. I found it in tools.

**Comment by Cleroth** [comment]
This is the version I use: https://mega.nz/#!5JMyBbrS!Z2uTGIduYtAj6DNWl1EK-fnvcYOBg6jEmVq9nTcWDcA

Alternatively, you can get an XP VM (if you have Win8 or 10) with the game here: https://dl.dropboxusercontent.com/content_link/HLcdvIL9sQ0HqdeYXlwdsvCodFU5sUlAXEHgYUuRG3EahTuSxY8SJ2oNwecQizyT/file?dl=1

**Comment by Cleroth** [comment]
Also you need to create/edit the `gng.ini` in the client folder with your server IP.

**Comment by Unessential** [comment]
Thank you. the file from your first link is password protected. What's the password for the file?

**Comment by Cleroth** [comment]
www.spgame.net

**Comment by Unessential** [comment]
Thanks.
