### ISSUE TITLE
buying element card in shop will freeze

### ISSUE THREAD

**Issue by tsuncp** [Cleroth/sp_server#8]
buying element card in shop will freeze

**Comment by whitearies** [comment]
That will be fixed while fixing all game modes bug

**Comment by tsuncp** [comment]
i wonder that if I continue to post bugs here, is it correct?

**Comment by Cleroth** [comment]
Sure, go ahead.

**Comment by tsuncp** [comment]
#14

**Comment by Cleroth** [comment]
Closed with #15
